# name of the software
name: FastMoE
theme: jekyll-docs-theme

project:
  version: 0.2.0
  download_url: https://github.com/laekov/fastmoe/releases
  download_text: Download

license:
  software: Apache-2.0 License
  software_url: https://opensource.org/licenses/Apache-2.0

  docs: CC BY 3.0
  docs_url: https://creativecommons.org/licenses/by/3.0/

links:
  header:
    - title: GitHub
      icon: github
      brand: true
      url: https://github.com/laekov/fastmoe
  homepage:
    - title: View on GitHub
      icon: github
      brand: true
      url: https://github.com/laekov/fastmoe
  footer:
    - title: GitHub
      icon: github
      brand: true
      url: https://github.com/laekov/fastmoe
    - title: Issues
      icon: bug
      url: https://github.com/laekov/fastmoe/issues?state=open

ui:
  mode: "auto" # 'auto', 'dark', 'light'
  brand:
    dark: "#DA70D6"
    light: "#9400D3"
  border_color:
    dark: "#5f5f5f"
    light: "#dee2e6"
  header:
    trianglify: true
    dark:
      color1: "#9932CC"
      color2: "#EE82EE"
    light:
      color1: "#8A2BE2"
      color2: "#DA70D6"
  masthead:
    color:
      dark: "#fff"
      light: "#fff"
    align:
      homepage: "center"
      page: "left"

social:
  github:
    user: laekov
    repo: fastmoe
  twitter:
    enabled: false
    via:
    hash:
    account:
  facebook:
    enabled: false
    profileUrl:

analytics:
  google: G-5XP4H6L5PX

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - jekyll-docs-theme.gemspec
  - LICENSE.md
  - README.md
  - screenshot.png
